name: Release
'on':
  workflow_call:
    secrets:
      ANSIBLE_GALAXY_API_TOKEN:
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install --disable-pip-version-check ansible

      - name: Set up Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 'lts/*'

      - name: Install semantic-release
        run: |
          npm install --global semantic-release@25 @semantic-release/exec@7 conventional-changelog-conventionalcommits@9

      - name: Configure semantic-release
        run: |
          echo '{"preset":"conventionalcommits","plugins":[["@semantic-release/commit-analyzer"],["@semantic-release/release-notes-generator"],["@semantic-release/github"],["@semantic-release/exec",{"publishCmd":"ansible-galaxy role import --api-key ${{ secrets.ANSIBLE_GALAXY_API_TOKEN }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)"}]]}' > .releaserc.json

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release
